### ISSUE TITLE
All Pages not found

### ISSUE THREAD

**Issue by franklinovic** [VisualAppeal/connect#5]
@thelfensdrfer 
I followed all installation steps described in readme. 
But, when i try to lunch application on http://localhost/connect/public or http://195.154.6.171/connect/public, the Auth middleware redirect to route /account/login which returns 
"The requested URL /connect/public/account/login was not found on this server." 
Please find attached screen captures.

Please, are there other config to do?

![connect_screen1](https://cloud.githubusercontent.com/assets/3253651/10902213/d79e1c50-81fa-11e5-9c85-51f9065854fb.png)
![connect_screen2](https://cloud.githubusercontent.com/assets/3253651/10902214/d7b63808-81fa-11e5-922f-2d8ba0f5ac79.png)

**Comment by thelfensdrfer** [comment]
Hi, it seems to work now? I think you just missed to configure your webserver. It's not mentioned in the readme yet. At the laravel docs you can find some help for this http://laravel.com/docs/5.0/installation#pretty-urls

**Comment by franklinovic** [comment]
.htaccess solved the issue.
Thank.
